//#define SECRET_SSID "WiFi-Vodafone-Dants"
//#define SECRET_PASS "Na0 gosto de pessoas em casa."
#define SECRET_SSID "AndroidAP3386"
#define SECRET_PASS "167c1bd8376e"
//#define SECRET_SSID "ISTAR-IUL-WIFI"
//#define SECRET_PASS "!P3d3P0rF4v0r#"
//#define SECRET_SSID "ISCTE-IUL-Guest"
//#define SECRET_PASS "9po6sSIvelmeNte"
//#define SECRET_SSID "LoRa_Lab_WiFi"
//#define SECRET_PASS "iscteloralab#1"

//#define SECRET_USERMQTT "client"
//#define SECRET_PASSMQTT "Master_password30"
#define SECRET_USERMQTT "sensor_ac3"
#define SECRET_PASSMQTT "Pass_sensor_ac3"
